<?php
/**
 * Created by PhpStorm.
 * User: kostya
 * Date: 23.04.2017
 * Time: 22:21
 */

namespace app\components;
use yii\base\Widget;
use app\models\Category;
use Yii;


class MenuWidget extends Widget
{
    public $tpl;
    public $data;
    public $menuHtml;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if ($this->tpl === null){
            $this->tpl = "menu";
        }
        $this->tpl .= '.php';
    }

    public function run()
    {
        //get cache
        $menu = Yii::$app->cache->get('menu');
        if ($menu) return $menu;//get cache

        $this->data = Category::find()->indexBy('category_id')->asArray()->all();
        $this->menuHtml = $this->getMenuHtml($this->data);
//        var_dump($this->data);

        //set cache
        YII::$app->cache->set('menu', $this->menuHtml, 60);//set cache

        return $this->menuHtml;
    }

    protected function getMenuHtml($data){
        $str = "";
        foreach ($data as $category){
            $str .= $this->catToTemplate($category);
        }
//        var_dump($str);
        return $str;
    }
    protected function catToTemplate($category){
        ob_start();
        include __DIR__ . '/menu_tpl/'. $this->tpl;
        return ob_get_clean();
    }
}